# Generated by Django 3.1.5 on 2022-04-17 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1500)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_offer', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='items')),
                ('price', models.PositiveSmallIntegerField()),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('available', models.BooleanField(default=True, verbose_name='Availability')),
                ('soft_delete', models.BooleanField(default=False, editable=False)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
            options={
                'verbose_name_plural': 'Items/Products',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.country')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('table_id', models.CharField(max_length=150)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_ammount', models.PositiveSmallIntegerField(editable=False)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', django_fsm.FSMIntegerField(choices=[(0, 'PENDING'), (1, 'ACCEPTED'), (2, 'CANCELLED')], default=0)),
                ('items', models.ManyToManyField(blank=True, related_name='order_items', to='core.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'All Orders',
                'ordering': ['added_on'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shop'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('items', models.ManyToManyField(blank=True, related_name='cart_items', to='core.Item')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AcceptedOrders',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Accepted Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.order',),
        ),
        migrations.CreateModel(
            name='CancelledOrders',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Cancelled Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.order',),
        ),
        migrations.CreateModel(
            name='OrdersRequestedCancellation',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Cancel Requests',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.order',),
        ),
        migrations.CreateModel(
            name='OrdersToday',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Orders Today',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.order',),
        ),
    ]
