# Generated by Django 3.1.5 on 2022-04-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220408_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='on_offer',
            field=models.BooleanField(default=False),
        ),
    ]
