# Generated by Django 3.1.5 on 2022-03-18 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220318_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name_plural': 'Items/Products'},
        ),
        migrations.RenameField(
            model_name='item',
            old_name='user',
            new_name='added_by',
        ),
    ]
