# Generated by Django 3.1.5 on 2022-05-27 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220524_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='on_offer',
            new_name='special',
        ),
    ]
