# Generated by Django 3.1.5 on 2022-03-19 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_item_soft_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='soft_delete',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
