# Generated by Django 3.1.5 on 2022-03-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220320_0443'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersRequestedCancellation',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Cancellation Order Requests',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.order',),
        ),
        migrations.AddField(
            model_name='item',
            name='offers',
            field=models.BooleanField(default=False),
        ),
    ]
