# Generated by Django 3.1.5 on 2022-04-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220330_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedOrders',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Accepted Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.order',),
        ),
        migrations.CreateModel(
            name='CancelledOrders',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Cancelled Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.order',),
        ),
        migrations.AlterModelOptions(
            name='ordersrequestedcancellation',
            options={'verbose_name_plural': 'Order Cancel Requests'},
        ),
        migrations.AddField(
            model_name='item',
            name='offerprice',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
