# Generated by Django 3.1.5 on 2022-04-12 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_cart_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordersrequestedcancellation',
            options={'verbose_name_plural': 'Cancel Requests'},
        ),
    ]
