# Generated by Django 3.1.5 on 2022-04-04 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20220404_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offers', models.BooleanField(default=False)),
                ('offerprice', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='offerprice',
        ),
        migrations.AlterField(
            model_name='item',
            name='offers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.offer'),
        ),
    ]
