# Generated by Django 3.1.5 on 2022-04-04 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20220404_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='offers',
        ),
        migrations.AddField(
            model_name='offer',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.item'),
            preserve_default=False,
        ),
    ]
