# Generated by Django 3.1.5 on 2022-04-04 15:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20220404_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offer_added_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
