# Generated by Django 3.1.5 on 2022-04-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_offer_offer_added_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='offers',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
