# Generated by Django 3.1.5 on 2022-04-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20220404_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='offers',
            field=models.BooleanField(default=False, verbose_name='On_Offer'),
        ),
    ]
