# Generated by Django 3.1.5 on 2022-04-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20220404_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='offerprice',
            field=models.PositiveSmallIntegerField(default=12),
            preserve_default=False,
        ),
    ]
