# Generated by Django 3.1.5 on 2022-04-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_item_offerprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='offerprice',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
