# Generated by Django 3.1.5 on 2022-04-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20220405_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Requested Cancellation'),
        ),
    ]
