# Generated by Django 3.1.5 on 2022-04-15 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220406_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
            ],
            options={
                'verbose_name_plural': 'CUSTOMERS',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
            ],
            options={
                'verbose_name_plural': 'STAFF',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'ADMIN'},
        ),
        migrations.DeleteModel(
            name='User_Address',
        ),
    ]
