# Generated by Django 3.1.5 on 2022-03-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='description',
            field=models.CharField(max_length=1500),
        ),
    ]
