# Generated by Django 3.1.5 on 2022-04-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_auto_20220413_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='subject',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
